export default FrameData = [
  {
      name: "Mario",
      jab1: {
        startup: "2",
        onShield: "-14",
        active: "--",
        total: "19",
        baseDamage: "2.2%",
        shieldLag: "8",
        shieldStun: "3",
      },
      jab2: {
        startup: "2",
        onShield: "-16",
        active: "--",
        total: "21",
        baseDamage: "1.7%",
        shieldLag: "5",
        shieldStun: "3",
      },
      jab3: {
        startup: "3",
        onShield: "-29",
        active: "--",
        total: "33",
        baseDamage: "4.0%",
        shieldLag: "11",
        shieldStun: "5",
      },
      fTilt: {
        startup: "5",
        onShield: "-13",
        active: "--",
        total: "25",
        baseDamage: "7.0%",
        shieldLag: "7",
        shieldStun: "7",
      },
      upTilt: {
        startup: "5",
        onShield: "-18",
        active: "--",
        total: "29",
        baseDamage: "5.5%",
        shieldLag: "6",
        shieldStun: "6",
      },
      downTilt: {
        startup: "5",
        onShield: "-15/-16",
        active: "--",
        total: "27",
        baseDamage: "7.0%/5.0%",
        shieldLag: "7/6",
        shieldStun: "7/6",
      },
      dashAttack: {
        startup: "6",
        onShield: "-17",
        active: "--",
        total: "37",
        baseDamage: "8.0%/6.0%",
        shieldLag: "9/8",
        shieldStun: "14/11",
      },
      forwardSmash: {
        startup: "15",
        onShield: "-22/-20",
        active: "--",
        total: "47",
        baseDamage: "17.7%/14.6%",
        shieldLag: "11/10",
        shieldStun: "12/10",
      },
      upSmash: {
        startup: "9",
        onShield: "-20",
        active: "--",
        total: "39",
        baseDamage: "14.0%",
        shieldLag: "10",
        shieldStun: "10",
      },
      downSmash: {
        startup: "5/14",
        onShield: "-31/-21",
        active: "--",
        total: "43",
        baseDamage: "10.0%/12.0%",
        shieldLag: "8/9",
        shieldStun: "7/8",
      },
      nair: {
        startup: "3",
        onShield: "-2/-3",
        active: "--",
        total: "45",
        baseDamage: "8.0%/5.0%",
        landingLag: "6",
        shieldLag: "7/6",
        shieldStun: "4/3",
      },
      fair: {
        startup: "16",
        onShield: "-12/-13",
        active: "--",
        total: "59",
        baseDamage: "14.0%/12.0%",
        landingLag: "17",
        shieldLag: "10/9",
        shieldStun: "5",
      },
      bair: {
        startup: "6",
        onShield: "-2/-3",
        active: "--",
        total: "33",
        baseDamage: "10.5%/7.0%",
        landingLag: "6",
        shieldLag: "8/7",
        shieldStun: "4/3",
      },
      dair: {
        startup: "5/7/9/11/13/23",
        onShield: "-11",
        active: "--",
        total: "37",
        baseDamage: "1.3%/5.5%",
        landingLag: "15",
        shieldLag: "4/6/4",
        shieldStun: "2/3/3",
      },
      upAir: {
        startup: "4",
        onShield: "-3",
        active: "--",
        total: "30",
        baseDamage: "7.0%/5.9%",
        landingLag: "6",
        shieldLag: "7/6",
        shieldStun: "3/3",
      },
      neutralB: {
        name: "Fireball",
        startup: "17",
        onShield: "-23",
        active: "disappears on frame 88",
        total: "49",
        baseDamage: "5.0%/4.0%",
        shieldLag: "6/5",
        shieldStun: "3/2",
      },
      sideB: {
        name: "Cape",
        startup: "12",
        onShield: "-16",
        active: "--",
        total: "35",
        baseDamage: "7.0%",
        shieldLag: "7",
        shieldStun: "7",
      },
      upB: {
        name: "Super Jump Punch",
        startup: "3/7/9/11/13/15/17",
        onShield: "--",
        active: "--",
        total: "--",
        baseDamage: "5.0%/0.6%/3.0%",
        shieldLag: "6/4/5",
        shieldStun: "6/2/4",
      },
      downB: {
        name: "F.L.U.D.D.",
        startup: "2 (+19)",
        onShield: "--",
        active: "--",
        total: "48",
        baseDamage: "--",
        shieldLag: "--",
        shieldStun: "--",
      },
      grab: {
        startup: "6",
        total: "34",
        baseDamage: "--",
      },
      dashGrab: {
        startup: "9",
        total: "42",
        baseDamage: "--",
      },
      pivotGrab: {
        startup: "10",
        total: "36",
        baseDamage: "--",
      },
      pummel: {
        startup: "1",
        total: "19",
        baseDamage: "1.3%",
      },
      fThrow: {
        startup: "13",
        total: "27",
        baseDamage: "8.0%",
      },
      bThrow: {
        startup: "44",
        total: "59",
        baseDamage: "11.0%",
      },
      upThrow: {
        startup: "16",
        total: "39",
        baseDamage: "7.0%",
      },
      downThrow: {
        startup: "18",
        total: "39",
        baseDamage: "5.0%",
      },
      spotDodge: {
        total: "20/25",
        invulnerable: "3-17",
      },
      fRoll: {
        total: "29",
        invulnerable: "4-15",
      },
      bRoll: {
        total: "34",
        invulnerable: "5-16",
      },
      nairDodge: {
        total: "52",
        invulnerable: "3-29",
        landingLag: "10",
      },
      dairDodge: {
        total: "71",
        landingLag: "11-19",
        invulnerable: "3-21",
      },
      diagonallyDownDodge: {
        total: "77",
        landingLag: "11-19",
        invulnerable: "3129",
      },
      sideDodge: {
        total: "87",
        landingLag: "11-19",
        invulnerable: "3-21",
      },
      diagonallyUpDodge: {
        total: "102",
        landingLag: "11-19",
        invulnerable: "3-21",
      },
      upAirDodge: {
        total: "116",
        landingLag: "11-19",
        invulnerable: "3-21",
      },
      misc: {
        weight: "98",
        gravity: "0.087",
        walkSpeed: "1.155",
        runSpeed: "1.76",
        initialDash: "1.936",
        airSpeed: "1.208",
        airAcceleration: "0.08",
        fallFastFall: "1.5 / 2.4",
        oosUpB: "3",
        oosNair: "6",
        oosFair: "7",
        shieldGrab: "10",
        shieldDrop: "11",
        jumpSquat: "3",
      }
  },
  {
      name: "Donkey Kong",
      jab1: "Startup: 5 frames, Total: 24 frames",
      jab2: "Startup: 4 frames, Total: 34 frames",
      jab3: "N/A",
      fTilt: "Startup: 7 frames, Total: 34 frames"
  }
];
